# Site settings
title: 勰门歪道
SEOTitle: 勰门歪道 | Shane Blog      #你的博客 | Your Blog
header-img: img/home-bg.jpg
email: lshane1985@gmail.com
description: "这里是 Shane 的个人博客"
keyword: "刘勰, Shane, 勰门歪道, 博客, 个人网站, 互联网, 产品, 管理, 用户增长"
url: "http://liuxie63.com"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog' "/huxblog-boilerplate"



# SNS settings
RSS: false
weibo_username:     shane2u
zhihu_username:     shane.liu
github_username:    shaneliu
#twitter_username:  huxpro
facebook_username:  Shane Liu



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: shane-liu    #_your_disqus_short_name_

# Duoshuo settings
#duoshuo_username: huxblog
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: false            # set to false if you want to use Comment without Sharing




# Analytics settings
# Baidu Analytics
ba_track_id: 765688f085c30c29a244139d363d8ae2        #4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "读书，写字 </br> 假设，实验，总结 </br> 如此往复就是完美的生活"
sidebar-avatar: /img/blog-avatar.jpeg #http://ojpjap8gl.bkt.clouddn.com/2017/05/09/149432436506303196.jpeg   # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Friends
#friends: [
#    {
#        title: "Hux Blog",
#        href: "http://huangxuan.me"
#    },{
#        title: "Foo",
#        href: "#"
#    },{
#        title: "Bar",
#        href: "#"
#    },{
#        title: "Example Friends",
#        href: "#"
#    },{
#        title: "It helps SEO",
#        href: "#"
#    }
#]
